# Generated by Django 5.2.2 on 2025-06-08 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerinfo',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='api.gamesession'),
        ),
        migrations.CreateModel(
            name='FloorHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField()),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='floor_history', to='api.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='NonCombatFloorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_type', models.CharField(blank=True, choices=[('Treasure', 'Treasure'), ('Treasure with Trap', 'Treasure With Trap'), ('Hidden Trap', 'Hidden Trap'), ('NPC Encounter', 'Npc Encounter')], max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('penalty', models.FloatField(default=0)),
                ('completion_rate', models.IntegerField(default=0)),
                ('floor_history_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='non_combat_floor', to='api.floorhistorymodel')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='non_combat_floor', to='api.gamesession')),
            ],
        ),
    ]
