# Generated by Django 5.2.2 on 2025-06-09 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_playerinfo_session_floorhistorymodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameevent',
            name='role',
            field=models.CharField(choices=[('Player', 'Player'), ('Narrator', 'Narrator'), ('System', 'System')], default='Narrator', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='game_state',
            field=models.CharField(choices=[('Player Creation', 'Player Creation'), ('In Progress', 'In Progress'), ('Waiting for Next Floor', 'Waiting For Next Floor'), ('Completed', 'Completed')], default='In Progress', max_length=25),
        ),
        migrations.AlterField(
            model_name='noncombatfloormodel',
            name='floor_history_model',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='non_combat_floor_model', to='api.floorhistorymodel'),
        ),
        migrations.AlterField(
            model_name='noncombatfloormodel',
            name='floor_type',
            field=models.CharField(choices=[('Treasure', 'Treasure'), ('Treasure with Trap', 'Treasure With Trap'), ('Hidden Trap', 'Hidden Trap'), ('NPC Encounter', 'Npc Encounter')], default='Treasure', max_length=20),
        ),
        migrations.AlterField(
            model_name='noncombatfloormodel',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='non_combat_floor_model', to='api.gamesession'),
        ),
    ]
