# Generated by Django 5.2.2 on 2025-06-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_gameevent_role_alter_gamesession_game_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='current_floor',
            field=models.IntegerField(default=0),
        ),
    ]
