# Generated by Django 5.2.2 on 2025-06-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_gamesession_current_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameevent',
            name='suggested_actions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
