services:
    ollama:
        build:
            context: .
            dockerfile: ollama/Dockerfile
        volumes:
            - ollama:/root/.ollama
        ports:
            - "11435:11435"
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]

    backend:
        build:
            context: backend
            dockerfile: Dockerfile
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        env_file:
            - ./.env.dev
        command: sh -c "cd /app/backend && dos2unix ./entrypoint.sh && chmod +x ./entrypoint.sh && ./entrypoint.sh"

    frontend:
        build:
            context: frontend 
            dockerfile: Dockerfile
        volumes:
            - ./frontend:/frontend
        ports:
            - "5173:5173"
        env_file:
            - ./.env.dev
        command: sh -c "cd /frontend && dos2unix ./entrypoint.sh && chmod +x ./entrypoint.sh && ./entrypoint.sh"

volumes:
    ollama:
