services:
    ollama:
        build:
            context: .
            dockerfile: docker/Dockerfile.ollama
        volumes:
            - ollama:/root/.ollama
        ports:
            - "11435:11435"
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]

    backend:
        build:
            context: .
            dockerfile: docker/Dockerfile.backend
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        command: sh -c "cd /app/backend && dos2unix ./entrypoint.sh && chmod +x ./entrypoint.sh && ./entrypoint.sh"

    frontend:
        build:
            context: .
            dockerfile: docker/Dockerfile.frontend
        volumes:
            - .:/app
        ports:
            - "5173:5173"
        command: sh -c "cd /app/frontend && dos2unix ./entrypoint.sh && chmod +x ./entrypoint.sh && ./entrypoint.sh"

volumes:
    ollama:
