services:
    ollama:
        build:
            context: .
            dockerfile: ollama/Dockerfile
        volumes:
            - ollama:/root/.ollama
        ports:
            - "11435:11435"
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]

    backend-prod:
        build:
            context: .
            dockerfile: backend/Dockerfile.prod
        ports:
            - "8001:8001"
        env_file:
            - ./.env.prod

    frontend:
        build:
            context: .
            dockerfile: frontend/Dockerfile
        volumes:
            - ./frontend:/frontend
        ports:
            - "5173:5173"
        env_file:
            - ./.env.prod
        command: sh -c "cd /frontend && dos2unix ./entrypoint.sh && chmod +x ./entrypoint.sh && ./entrypoint.sh"

volumes:
    ollama:
