services:
    ollama:
        build:
            context: .
            dockerfile: docker/Dockerfile.ollama
        volumes:
            - ollama:/root/.ollama
        ports:
            - "11435:11435"
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]

    backend:
        build:
            context: .
            dockerfile: docker/Dockerfile.backend
        depends_on:
            - ollama
        volumes:
            - .:/app
        ports:
            - "8000:8000"

    frontend:
        build:
            context: .
            dockerfile: docker/Dockerfile.frontend
        depends_on:
            - backend
        volumes:
            - .:/app
        ports:
            - "5173:5173"

volumes:
    ollama:
