version: '3.8'

services:
  ollama:
    build:
      context: .
      dockerfile: docker/Dockerfile.ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    depends_on:
      - ollama
    volumes:
      - .:/home/backend/app
    tty: true
    stdin_open: true
    command: /bin/bash

volumes:
  ollama:


