FROM node:24-slim

# Set working directory
WORKDIR /app

COPY frontend/package.json /app/frontend/package.json

COPY frontend/entrypoint.sh /app/frontend/entrypoint.sh
ENTRYPOINT [ "/app/frontend/entrypoint.sh" ]
